version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_FIREBASE_API_KEY=AIzaSyBteDUmy1OeeeDn_QLFpqgNb0o2r2-Np6I
      - REACT_APP_FIREBASE_AUTH_DOMAIN=voicegif.firebaseapp.com
      - REACT_APP_FIREBASE_PROJECT_ID=voicegif
      - REACT_APP_FIREBASE_STORAGE_BUCKET=voicegif.appspot.com
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=498099891610
      - REACT_APP_FIREBASE_APP_ID=1:498099891610:web:ada14f0b624dbc858a9e23
      - REACT_APP_MEASUREMENT_ID=G-9FS4JSNMP4
      - REACT_APP_BACKEND_URL=http://localhost:8888/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    environment:
      - PORT=8888
      - TELEGRAM_TOKEN=5472499049:AAEq_tiKc44PkHybxB35crkvf-vUBrOGAxI
      - TELEGRAM_CHAT_ID=-1001704750910
